-- liquibase formatted sql

-- changeset ammar:LIQUIBASE_EX-1
CREATE TABLE LIQUIBASE_EX (ID int primary key, NAME varchar(50) not null);
INSERT INTO LIQUIBASE_EX (ID, NAME) VALUES (101, 'ammar') ;
INSERT INTO TABLE_LOAD_CONTROL (SOURCE_SYSTEM, TABLE_NAME, ENV_NAME, TABLE_SOURCE, LOAD_STRATEGY, ETL_STATUS, ETL_EXECUTION_STATUS, T1_MAX_LOAD_END_DATE, T2_MAX_LOAD_END_DATE, T3_STATUS, T3_CLUSTER_ID, T3_BUCKET, T3_DATABASE, T3_TABLE_TYPE, T3_FORMAT, UPDATE_DATE, UPDATED_BY) VALUES ('OracleERP', 'LIQUIBASE_EX', 'SBX', 'HIVE', 'FLAT', 'TODO', 'TODO', '2021-01-01', '2021-01-01', 'TODO', 'GDA_SBX_S3', 'gda-sbx-lake-m1-refined-zone', 'docusign_refined_mockdb', 'S3', 'json', CURRENT_TIMESTAMP(), 'ammar') ;
UPDATE RAW_FILES SET PROCESSED_DATE = NULL WHERE SOURCE_SYSTEM = 'OracleERP' AND TABLE_NAME = 'AR_ADJUSTMENTS_ALL' AND ENV_NAME = 'SBX' AND OBJECT_NAME = 'finance/incoming/mock_AR_ADJUSTMENTS_ALL_2021-05-21_00_31_58.txt' ;
DELETE FROM TABLE_QUALITY_CONTROL WHERE SOURCE_SYSTEM = 'OracleERP' AND TABLE_NAME = 'T3_SAMPLE_SQL' AND ENV_NAME = 'SBX' ;
-- rollback DROP TABLE LIQUIBASE_EX;
-- rollback DELETE FROM TABLE_LOAD_CONTROL WHERE SOURCE_SYSTEM = 'OracleERP' AND TABLE_NAME = 'LIQUIBASE_EX' AND ENV_NAME = 'SBX' ;
-- rollback INSERT INTO TABLE_QUALITY_CONTROL (SOURCE_SYSTEM, TABLE_NAME, ENV_NAME, DQ_STATUS, T3_STATUS, T3_CLUSTER_ID, UPDATE_DATE, UPDATED_BY) VALUES ('OracleERP', 'T3_SAMPLE_SQL', 'SBX', 'TODO', 'TODO', 'GDA_SBX_S3', CURRENT_TIMESTAMP(), 'ammar') ;
